unicode = str
basestring = str
logger = ...
_u2l_obj_cache = ...

def unicode_to_latex(
    s,
    non_ascii_only=...,
    replacement_latex_protection=...,
    unknown_char_policy=...,
    unknown_char_warning=...,
): ...

utf82latex = ...

def utf8tolatex(
    s, non_ascii_only=..., brackets=..., substitute_bad_chars=..., fail_bad_chars=...
): ...
