unicode = str
basestring = str
logger = ...

def get_builtin_uni2latex_dict():  # -> MappingProxyType[int, str] | dict[int, str]:
    ...

RULE_DICT = ...
RULE_REGEX = ...
RULE_CALLABLE = ...

class UnicodeToLatexConversionRule:
    def __init__(
        self, rule_type, rule=..., replacement_latex_protection=...
    ) -> None: ...
    def __repr__(self):  # -> str:
        ...

def get_builtin_conversion_rules(
    builtin_name,
):  # -> list[UnicodeToLatexConversionRule]:
    ...

class UnicodeToLatexEncoder:
    def __init__(self, **kwargs) -> None: ...
    def unicode_to_latex(self, s): ...
