def unicode(s): ...

_basestring = ...
_str_from_unicode = ...
_unicode_from_str = ...

class MacroSpec:
    def __init__(self, macroname, args_parser=..., **kwargs) -> None: ...
    def parse_args(self, *args, **kwargs): ...
    def __repr__(self): ...

class EnvironmentSpec:
    def __init__(
        self, environmentname, args_parser=..., is_math_mode=..., **kwargs
    ) -> None: ...
    def parse_args(self, *args, **kwargs): ...
    def __repr__(self): ...

class SpecialsSpec:
    def __init__(self, specials_chars, args_parser=..., **kwargs) -> None: ...
    def parse_args(self, *args, **kwargs): ...
    def __repr__(self): ...

def std_macro(macname, *args, **kwargs): ...
def std_environment(envname, *args, **kwargs): ...
def std_specials(specials_chars): ...

class LatexContextDb:
    def __init__(self, **kwargs) -> None: ...
    def add_context_category(
        self,
        category,
        macros=...,
        environments=...,
        specials=...,
        prepend=...,
        insert_before=...,
        insert_after=...,
    ): ...
    def set_unknown_macro_spec(self, macrospec): ...
    def set_unknown_environment_spec(self, environmentspec): ...
    def set_unknown_specials_spec(self, specialsspec): ...
    def categories(self): ...
    def get_macro_spec(self, macroname): ...
    def get_environment_spec(self, environmentname): ...
    def get_specials_spec(self, specials_chars): ...
    def test_for_specials(self, s, pos, parsing_state=...): ...
    def iter_macro_specs(self, categories=...): ...
    def iter_environment_specs(self, categories=...): ...
    def iter_specials_specs(self, categories=...): ...
    def filter_context(
        self, keep_categories=..., exclude_categories=..., keep_which=...
    ): ...
