from pylatexenc.latexwalker import LatexGroupNode

def unicode(s): ...

_basestring = ...
_str_from_unicode = ...
_unicode_from_str = ...

class ParsedMacroArgs:
    argnlist: list[LatexGroupNode | None] | None
    argspec: str | list[str] | None
    def __init__(
        self,
        argnlist: list[LatexGroupNode | None] | None = ...,
        argspec: str | list[str] | None = ...,
        **kwargs: object,
    ) -> None: ...
    def to_json_object(self):  # -> dict[str, str]:
        ...
    def __repr__(self):  # -> str:
        ...

class MacroStandardArgsParser:
    def __init__(
        self, argspec=..., optional_arg_no_space=..., args_math_mode=..., **kwargs
    ) -> None: ...
    def parse_args(
        self, w, pos, parsing_state=...
    ):  # -> tuple[ParsedMacroArgs, Any, Any]:
        ...
    def __repr__(self):  # -> str:
        ...

class ParsedVerbatimArgs(ParsedMacroArgs):
    def __init__(
        self, verbatim_chars_node, verbatim_delimiters=..., **kwargs
    ) -> None: ...
    def __repr__(self):  # -> str:
        ...

class VerbatimArgsParser(MacroStandardArgsParser):
    def __init__(self, verbatim_arg_type, **kwargs) -> None: ...
    def parse_args(
        self, w, pos, parsing_state=...
    ):  # -> tuple[ParsedVerbatimArgs, Any, Any] | None:
        ...
    def __repr__(self):  # -> str:
        ...
