def unicode(string): ...

basestring = str
_latex_specs_placeholders = ...
_latex_specs_approximations = ...
_latex_specs_base = ...
advanced_symbols_macros = ...
specs = ...
unicode_accents_list = ...

def make_accented_char(node, combining, l2tobj):  # -> str:
    ...
